version: '3'

services:
  check-in:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: check-in-app
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    container_name: mysql
    ports:
      - '3306:3306'
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: prisma
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql

volumes: #define our mysql volume used above
  mysql:
